Repository axem-solutions/dem, pull requests merged in 2023-10, with the labels that each got.

#116 Update README.md for Hacktoberfest
  README.md
Labels: documentation

#121 v0.2.1 RELEASED
  pyproject.toml
Labels: release

#137 updated clone cmd to cp
  dem/cli/command/cp_cmd.py
  dem/cli/main.py
  docs/commands.md
  tests/cli/test_cp.py
Labels: hacktoberfest-accepted

#143 No ws condition in create cmd
  dem/cli/command/create_cmd.py
  tests/cli/test_create_cmd.py
Labels: hacktoberfest-accepted
